# Generated by Django 2.2.1 on 2019-05-19 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residencia', '0011_remove_residencia_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('semana_del_año', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reservas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_reservas', to=settings.AUTH_USER_MODEL)),
                ('residenciaQuePertence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_actual', to='residencia.Residencia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizacion', models.DateField(null=True)),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('subasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Subasta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
