# Generated by Django 2.2 on 2019-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
