# Generated by Django 2.2.1 on 2019-05-20 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0011_remove_residencia_is_active'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencia.Residencia'),
        ),
    ]
