# Generated by Django 2.2 on 2019-04-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_residencia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='residencia_id',
            new_name='residencia',
        ),
    ]
