# Generated by Django 2.2.1 on 2019-05-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_subasta_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subasta',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
