# Generated by Django 2.0.13 on 2019-05-18 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0006_remove_residencia_listadesemanas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0003_auto_20190430_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('reserva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reserva.Reserva')),
            ],
            bases=('reserva.reserva',),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reservas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='residenciaQuePertence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_actual', to='residencia.Residencia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puja',
            name='subasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Subasta'),
        ),
        migrations.AddField(
            model_name='puja',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
