# Generated by Django 2.1.7 on 2019-05-19 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20190518_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='residencia',
        ),
        migrations.AddField(
            model_name='reserva',
            name='semana_del_año',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subasta',
            name='finalizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reservas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='residenciaQuePertence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencia_actual', to='residencia.Residencia'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
