# Generated by Django 2.0.13 on 2019-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_remove_subasta_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
