# Generated by Django 2.0.13 on 2019-07-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_subasta_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0.0)),
                ('reserva', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva')),
            ],
        ),
    ]
