# Generated by Django 2.2.1 on 2019-07-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_reserva_in_hotsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='in_hotsale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
