# Generated by Django 2.0.13 on 2019-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_auto_20190713_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='in_hotsale',
            field=models.BooleanField(default=False),
        ),
    ]
