# Generated by Django 2.0.13 on 2019-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_auto_20190713_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva'},
        ),
        migrations.AddField(
            model_name='hotsale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
