# Generated by Django 2.2.1 on 2019-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_auto_20190714_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reservo_con_hotsale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
