# Generated by Django 2.0.13 on 2019-07-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_reserva_reservo_con_hotsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='reservo_con_hotsale',
            field=models.BooleanField(default=False),
        ),
    ]
