# Generated by Django 2.2 on 2019-04-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencia',
            old_name='id',
            new_name='auto_id',
        ),
    ]
