# Generated by Django 2.0.13 on 2019-05-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0003_residencia_capacidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencia',
            options={'verbose_name': 'Residencia', 'verbose_name_plural': 'Residencias'},
        ),
    ]
