# Generated by Django 2.0.13 on 2019-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0004_auto_20190511_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='listaDeSemanas',
            field=models.TextField(null=True),
        ),
    ]
