# Generated by Django 2.0.13 on 2019-05-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0005_residencia_listadesemanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='listaDeSemanas',
        ),
    ]
