# Generated by Django 2.1.7 on 2019-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0006_remove_residencia_listadesemanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
    ]
