# Generated by Django 2.2.1 on 2019-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0007_residencia_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
