# Generated by Django 2.0.13 on 2019-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0008_residencia_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
