# Generated by Django 2.2.1 on 2019-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0009_residencia_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
