# Generated by Django 2.2.1 on 2019-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencia', '0012_residencia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('precio', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='residencia',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='residencia',
            name='localidad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
