# Generated by Django 2.0.13 on 2019-06-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190519_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dni',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tarjeta_credito',
            field=models.IntegerField(null=True),
        ),
    ]
