# Generated by Django 2.0.13 on 2019-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190608_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tarjeta_credito',
            new_name='codigo_seguridad_tarjeta',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_vencimiento_tarjeta',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marca_tajeta',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_titular_tarjeta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_tarjeta_credito',
            field=models.IntegerField(null=True),
        ),
    ]
